JDP220401-25_
adrianpaz/project-jdp-2204-01 pull request #15
Opened 2022-04-07 22:51 UTC by gkowalczyk

2022-04-09 10:12 UTC, KarolinaMizgier commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "blockUserById")
@PutMapping(value = "/block/{userId}")

2022-04-09 19:58 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "blockUserById")
w commit #8 zmiana koncepcji UserControllera, zerknij teraz proszę :)

`@RequestMapping(method = RequestMethod.PUT)
    public ResponseEntity<UserDto> blockUser(@RequestBody UserDto userDto) {
        User user = userMapper.mapToUser(userDto);
        User userBlocked = userService.blockUser(user);
        return ResponseEntity.ok(userMapper.mapToUserDto(userBlocked));`

2022-04-09 22:32 UTC, dzejsiejcz requested changes
spoko pomysł z JWTToken

2022-04-09 22:32 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    public User generateKey(final User user) {
metoda niewykorzystana już, po implementacji JWTokena. Do usunięcia

2022-04-09 22:32 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE)
nie wiem czy to działa, nie testowałem, ale chyba styknie sama adn. @PostMapping bez @RequateMapping i okr. method =...

2022-04-09 22:32 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @RequestMapping(method = RequestMethod.PUT)
@PutMapping

2022-04-09 22:32 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<User> generateToken(@RequestParam("user") String username, @RequestParam("password") String key) {
Rozumiem, że parametry metody są rozwojowe, ale na ten moment nie wykorzystujesz "password"

2022-04-09 22:32 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @RequestMapping(method = RequestMethod.PUT)
oraz powinien być rzucony wyjątek UserNotFoundException, aktualnie ta klasa nie jest nigdzie wykorzystywana

2022-04-10 13:09 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    public User generateKey(final User user) {
tu fakt,  niepotrzebnie została,  poprawki naniesione #15

2022-04-10 13:10 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE)
tu fakt, niepotrzebnie została, poprawki naniesione #15

2022-04-10 13:16 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<User> generateToken(@RequestParam("user") String username, @RequestParam("password") String key) {
są zakończone, wykorzystuje -w metodzie @PostMapping("user") generuje token 
![Zrzut ekranu 2022-04-10 135839](https://user-images.githubusercontent.com/86222743/162619895-4947675a-8fc8-4612-bf52-4ca826d2bd56.png)
 jeśli użytkownik chce dostać odpowiedź np w metodzie @RequestMapping("check") , musi wpisać wygenerowany wcześniej token
![Zrzut ekranu 2022-04-10 140116](https://user-images.githubusercontent.com/86222743/162619994-9829f087-ead2-4ff1-84e4-c156ff438df1.png)

2022-04-10 17:55 UTC, dzejsiejcz requested changes

2022-04-10 17:55 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<User> generateToken(@RequestParam("user") String username, @RequestParam("password") String key) {
ok, co nie zmienia faktu, że @RequestParam("password") String key) jest nie wykorzystywane w metodzie, stąd niepotrzebne

2022-04-10 18:45 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<User> generateToken(@RequestParam("user") String username, @RequestParam("password") String key) {
![image](https://user-images.githubusercontent.com/86222743/162634366-6d02361e-82bc-4802-a0ee-5956f92a5bac.png)

> jest nie wykorzystywane w metodzie, stąd niepotrzebne

pole musi być jakkolwiek nazwane i musi istnieć ,abyś mógł skorzystać z przekazywania parametru "password" ,  nie widzisz tego bo nigdzie indziej w kodzie nie jest wykorzystywane. Jeśli usuniesz   @RequestParam("password") nie wygenerujesz token.Mam nadzieję że teraz już rozumiesz

2022-04-10 19:31 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<User> generateToken(@RequestParam("user") String username, @RequestParam("password") String key) {
![image](https://user-images.githubusercontent.com/67972266/162636409-dd473814-197a-4d19-b938-06fd705235d0.png)

sprawdziłem i po usunięciu parametru password działa to, co wkleiłeś :) zwraca token. Chyba że wciąż coś mi umyka...

2022-04-10 19:38 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<User> generateToken(@RequestParam("user") String username, @RequestParam("password") String key) {
Chodzi o interakcję użytkownika,  jak przy logowaniu, podajemy nie tylko nick  ( tutaj pole "username") , ale także hasło do logowania ( tutaj pole "password")

2022-04-10 19:44 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<User> generateToken(@RequestParam("user") String username, @RequestParam("password") String key) {
projekt nie narzuca tworzenia hasła, natomiast imho metoda powinna sprawdzać czy użytkownik o podanej nazwie istnieje - co możemy wdrożyć - a potem dopiero generować token lub nie. To wynika wprost z treści zadania

2022-04-11 18:27 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<User> generateToken(@RequestParam("user") String username, @RequestParam("password") String key) {
metody generują dla danego użytkownika klucz,  za pomocą którego następuje autoryzacja = symulacja logowania ,("po podaniu poprawnych danych użytkownika w rozumieniu klucz możesz wywołać np metodę @GetMapping") - myślę że to wystarczy bo to moja interpretacja.

2022-04-11 18:31 UTC, gkowalczyk reviewed
.

2022-04-11 20:11 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    // @ManyToOne(cascade = CascadeType.PERSIST)//// implementation after fix the database structure
to było zakomentowane , w #18 jest już ok i czeka na sprawdzenie

2022-04-12 13:09 UTC, dzejsiejcz approved these changes

2022-04-12 13:58 UTC, rafalcisz1991 approved these changes

2022-04-13 05:01 UTC, merged