First commit of branch -29
adrianpaz/project-jdp-2204-01 pull request #19
Opened 2022-04-11 15:33 UTC by rafalcisz1991

2022-04-11 15:33 UTC, rafalcisz1991 commented
Zgodnie z taskiem - drobne poprawki w ProductController i ProductMapper

2022-04-12 21:11 UTC, dzejsiejcz requested changes

2022-04-12 21:11 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                //product.getId(),
ta linijka nie powinna być zakomentowana

2022-04-12 21:11 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                //productDto.getId(),
dlaczego zakomentowane? lombock Data uwzględnia taki konstruktor

2022-04-14 15:14 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                //product.getId(),
Zmieniłem logikę tej metody.

2022-04-14 15:15 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                //productDto.getId(),
Ostatecznie usunąłem ten wiersz.

2022-04-14 16:44 UTC, dzejsiejcz approved these changes

2022-04-14 17:36 UTC, rafalcisz1991 commented
Ostatnie poprawki. Wstępnie każdy endpoint działa poprawnie w Postmanie.

2022-04-17 14:52 UTC, AgaChalat85 approved these changes

2022-04-18 07:35 UTC, merged