OrderController Endpoints dummy implemented, OrderDto created
adrianpaz/project-jdp-2204-01 pull request #2
Opened 2022-03-30 18:41 UTC by AgaChalat85

2022-04-01 20:05 UTC, dzejsiejcz requested changes

2022-04-01 20:05 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +@RequestMapping("api/v1/orders")
Może uzgodnijmy PATH: "v1/..."

2022-04-02 17:59 UTC, AgaChalat85 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +@RequestMapping("api/v1/orders")
ok, zmieniłam na "v1/orders"

2022-04-02 19:00 UTC, dzejsiejcz approved these changes

2022-04-03 18:46 UTC, adrianpaz approved these changes

2022-04-03 18:49 UTC, merged