Jdp220401 22
adrianpaz/project-jdp-2204-01 pull request #21
Opened 2022-04-12 22:49 UTC by kuba1306

2022-04-20 13:24 UTC, rafalcisz1991 reviewed
Komenty w środku

2022-04-20 13:24 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> -    //private final DbService dbService;
Planujesz 2 różne service'y dla Grup?

2022-04-20 13:24 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>  }
Patrzyłeś, czy przy nazwaniu danej klasy "GROUPS" pojawia się Tobie taka tabela w MySQL Workbeanch'u (linia 14) ?

Miałem z tym problem, o Adrian na ostatnim spotkaniu chyba zasugerował, żeby coś takiego nazwać, np. product_group(s) - tak jak w aktualnym mainie. Fraza GROUP(S) może nie być zaakceptowana jako nazwa encji, więc nie stworzy Tobie takiej tabli.

2022-04-20 13:24 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +public class GroupMapper {
Jeżeli dobrze pamiętam, to mapper'y chyba mają być oznaczone adnotacją @ Component. Ale możliwe, że nie zrozumiałem Adriana dobrze.

2022-04-20 13:35 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>  }
OK, widziałem w Twoim kolejnym branchu: Jdp220401 18, że faktycznie już zmieniłeś nazwę tabeli, także OK.

2022-04-21 18:14 UTC, rafalcisz1991 approved these changes

2022-04-21 18:41 UTC, gkowalczyk approved these changes

2022-04-21 18:48 UTC, dzejsiejcz requested changes

2022-04-21 18:48 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public ResponseEntity<GroupDto> addNewGroup(@RequestBody GroupDto groupDto) {
tu w returnie może tak jak tu return ResponseEntity.ok(OrderMapper.mapToOrderDto(order));

2022-04-21 18:57 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public ResponseEntity<GroupDto> addNewGroup(@RequestBody GroupDto groupDto) {
Ale tworzoną nową grupę musimy po raz kolejny mapować do obiektu DTO? Chyba ostatecznie ma być po prostu zapisana do bazy danych - więc cała metoda ostatecznie wywołana ok().build().

2022-04-21 19:32 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public ResponseEntity<GroupDto> addNewGroup(@RequestBody GroupDto groupDto) {
zapytajmy zamawiającego ;)

2022-04-22 10:45 UTC, dzejsiejcz approved these changes

2022-04-22 11:30 UTC, rafalcisz1991 commented
Jak patrzyłem w szczegóły build'a tutaj na Gicie, to błędy dotyczą tylko klasy GroupDto, częściowo wynikają z braku ";" na końcu jakiegoś wiersza, itd. Także raczej nic grubego.

![image](https://user-images.githubusercontent.com/94235108/164706296-feb925c7-a236-4aa8-9fcd-40c247381a71.png)

2022-04-22 18:49 UTC, merged