Jdp220401 18
adrianpaz/project-jdp-2204-01 pull request #27
Opened 2022-04-18 21:27 UTC by kuba1306

testy bez zależności, będę uzupełniał. Proszę o informację czy te podstawowe testy są wg was ok.

2022-04-21 19:05 UTC, dzejsiejcz requested changes

2022-04-21 19:05 UTC, dzejsiejcz commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +import org.junit.After;
użyj tych importów import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;

2022-04-21 19:05 UTC, dzejsiejcz commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +//    @Test
chyba możesz to odkomenować?

2022-04-21 19:50 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +//    @Test
Póki co zakomentowane bo nie przechodzi testów, muszę dopracować.

2022-04-21 19:54 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +import org.junit.After;
Niestety nie przechodzą mi zaproponowane przez Ciebie importy. Mogę użyć org.aspect.lang.adnotation albo właśnie org,junit

2022-04-22 17:40 UTC, rafalcisz1991 requested changes
Chyba trzeba zmienić sposób przypisywania konkretnych ID - do zmiennej, zamiast konkretne wartości przypisywane do metody.

2022-04-22 17:40 UTC, rafalcisz1991 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +        Group newGroup = groupRepository.findById(1L).get();
Wczoraj chyba padła sugestia, żeby nie wpisywać na sztywno numerków Id, tylko dane id przypisywać na bieżąco da jakiejś zmiennej.

2022-04-22 17:40 UTC, rafalcisz1991 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +        Group group1 = groupRepository.findById(2L).get();
J.w.

2022-04-24 10:24 UTC, gkowalczyk requested changes

2022-04-24 18:14 UTC, KarolinaMizgier commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +        Group newGroup = groupRepository.findById(1L).get();
Albo zamiast ID to porównywać wartości obiektów (np. nazwę, która może być unikatowo wymyślona na potrzebę testu i na pewno się nie powtórzy nikomu w lokalnej bazie danych)

2022-04-24 20:15 UTC, kuba1306 commented on build.gradle
dzięki dodane

2022-04-24 20:17 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +        Group newGroup = groupRepository.findById(1L).get();
[https://capture.dropbox.com/PQzQrtzYJ3mXEyLO](url)

2022-04-24 20:34 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +        Group newGroup = groupRepository.findById(1L).get();
https://capture.dropbox.com/To2CVKSyNaDcwLUA

u mnie przechodzi pojedynczko

2022-04-24 20:34 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testCreateNewGroup() {
https://capture.dropbox.com/ud4i4PBVlccCwtH5 pojedynczo

2022-04-24 20:35 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testCreateNewGroup() {
https://capture.dropbox.com/7yVS0X24gXYsyEaR wszystko na raz

2022-04-24 20:36 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testUpdateGroup() {
https://capture.dropbox.com/zFwvbqRL2OCIRoTW

2022-04-24 20:36 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testDeleteGroup() {
https://capture.dropbox.com/fUwqEknZR0gL1bpo

2022-04-24 20:36 UTC, kuba1306 commented on build.gradle
dziękuję dodane

2022-04-24 21:28 UTC, kuba1306 commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +import org.junit.After;
Zrobiłem tak jak zasugerowałaś i niestety przy użyciu adnotacji @BeforeEach nie tworzą mi się przed każdym testem grupy:"trousers" i "hats". Szukam przyczyny.

2022-04-24 23:03 UTC, kuba1306 commented
ręcznie dodałem grupy przed każdym z testów - niestety nie wiem dlaczego testy mi nie przechodzą gdy używam tych adnotacji. Zobaczcie proszę czy u was takie rozwiązanie jak teraz zastosowałem u Was działa.

2022-04-25 10:06 UTC, gkowalczyk commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +        Group newGroup = groupRepository.findById(1L).get();
zrób jeszcze raz commit po zmianach , sprawdzę :)

2022-04-25 10:07 UTC, gkowalczyk commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testCreateNewGroup() {
zrób jeszcze raz commit po zmianach , sprawdzę :)

2022-04-25 10:07 UTC, gkowalczyk commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testUpdateGroup() {
zrób jeszcze raz commit po zmianach , sprawdzę :)

2022-04-25 10:07 UTC, gkowalczyk commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testDeleteGroup() {
zrób jeszcze raz commit po zmianach , sprawdzę :)

2022-04-25 10:12 UTC, gkowalczyk commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +        Group newGroup = groupRepository.findById(1L).get();
na najnowszych zmianach z Twojego branch,  baza wyczyszczona przed testem
![image](https://user-images.githubusercontent.com/86222743/165069122-9cfe2618-479d-412b-9b7a-56b51122b114.png)

2022-04-25 10:12 UTC, gkowalczyk commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testCreateNewGroup() {
na najnowszych zmianach z Twojego branch,  baza wyczyszczona przed testem
![image](https://user-images.githubusercontent.com/86222743/165069122-9cfe2618-479d-412b-9b7a-56b51122b114.png)

2022-04-25 10:12 UTC, gkowalczyk commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testUpdateGroup() {
na najnowszych zmianach z Twojego branch,  baza wyczyszczona przed testem
![image](https://user-images.githubusercontent.com/86222743/165069122-9cfe2618-479d-412b-9b7a-56b51122b114.png)

2022-04-25 10:12 UTC, gkowalczyk commented on src/test/java/com/kodilla/ecommercee/domain/GroupTestSuite.java
> +    public void testDeleteGroup() {
na najnowszych zmianach z Twojego branch,  baza wyczyszczona przed testem
![image](https://user-images.githubusercontent.com/86222743/165069122-9cfe2618-479d-412b-9b7a-56b51122b114.png)

2022-04-25 20:12 UTC, closed without merging

2022-04-25 20:12 UTC, kuba1306 commented
JDP220401-18tests is actual for this task