JDP220401-25
adrianpaz/project-jdp-2204-01 pull request #8
Opened 2022-04-05 15:10 UTC by gkowalczyk

2022-04-05 20:41 UTC, dzejsiejcz requested changes

2022-04-05 20:41 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity <List<UserDto>> getAllUsers() {
metoda ta jest niepotrzebna, zamawiający tej funkcji/endpointa nie wskazał, jestem za usunięciem

2022-04-05 20:41 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public  ResponseEntity<UserDto> getUser(@PathVariable Long userId) throws UserNotFoundException {
metoda ta jest niepotrzebna, zamawiający tej funkcji/endpointa nie wskazał, jestem za usunięciem

2022-04-05 20:41 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<UserDto> blockUserId (@RequestBody UserDto userDto ) {
"/blockuser" lub poprostu "/block" powinno być

2022-04-05 20:41 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +public interface UserRepository extends CrudRepository<User, Long> {
analogicznie niepotrzebne metody, wg dokumentacji potrzebne są
 	•	users:
	◦	utworzenie użytkownika
	◦	zablokowanie użytkownika
	◦	wygenerowanie losowego klucza ważnego godzinę po podaniu poprawnych danych użytkownika

2022-04-05 20:41 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +public class UserService {
tu tez wystarczy save user, chyba że nie rozumiem :)

2022-04-06 14:52 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity <List<UserDto>> getAllUsers() {
usunięto

2022-04-06 14:54 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public  ResponseEntity<UserDto> getUser(@PathVariable Long userId) throws UserNotFoundException {
usunięto

2022-04-06 14:54 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    public ResponseEntity<UserDto> blockUserId (@RequestBody UserDto userDto ) {
poprawa

2022-04-06 14:54 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +public interface UserRepository extends CrudRepository<User, Long> {
jeżeli to usunę to nie zadziała metoda @GetMapping("/getToken/{userId}"), na razie musi zostać

2022-04-06 14:55 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +public class UserService {
jeżeli to usunę to nie zadziała metoda @GetMapping("/getToken/{userId}"), na razie musi zostać

2022-04-06 16:08 UTC, rafalcisz1991 requested changes
1 sugestia w controlerze

2022-04-06 16:08 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +    User save(User user);
Nie wyskakuje Tobie komunikat o "unchecked overriding", gdy próbujesz nadpisać tę konretną metodę?

Razem z podświetleniem się typu User na żółto?

2022-04-06 17:03 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +    User save(User user);
nie, wszystko ok

2022-04-06 17:05 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> -        SpringApplication.run(EcommerceeApplication.class, args);
Tej zmiany nie powinno być

2022-04-06 17:05 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> -public class GroupController {
Dlaczego usuwasz istniejące kontrolery?

2022-04-06 17:41 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> -public class GroupController {
przywrócono

2022-04-06 18:09 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> +    }
ok

2022-04-06 18:11 UTC, gkowalczyk commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PutMapping
poprawa

2022-04-06 18:13 UTC, gkowalczyk commented on src/main/resources/application.properties
> +spring.datasource.driver-class-name=org.h2.Driver
poprawa

2022-04-07 19:17 UTC, closed without merging