Jdp220401 13
adrianpaz/project-jdp-2204-01 pull request #9
Opened 2022-04-05 21:06 UTC by kuba1306

2022-04-06 20:05 UTC, AgaChalat85 requested changes
Chyba brakuje GroupRepository( w treści zadania jest napisane"Utwórz encję i jej repozytorium"):
Pozostałe komentarze w kodzie.

2022-04-06 20:05 UTC, AgaChalat85 commented on src/main/java/com/kodilla/ecommercee/service/DbService.java
> +public class DbService {
To nie należy do tego taska.

2022-04-06 20:05 UTC, AgaChalat85 commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +public class GroupService {
To nie należy do tego taska,

2022-04-07 13:23 UTC, kuba1306 commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> +import com.kodilla.ecommercee.dto.GroupDto;
poprawione

2022-04-07 13:24 UTC, kuba1306 commented on src/main/java/com/kodilla/ecommercee/service/DbService.java
> +public class DbService {
poprawione

2022-04-08 10:15 UTC, AgaChalat85 requested changes

2022-04-08 10:15 UTC, AgaChalat85 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @ManyToOne
tutaj jest zła relacja. Powinno być @OneToMany

2022-04-09 11:42 UTC, adrianpaz commented on build.gradle
> +    implementation 'mysql:mysql-connector-java:8.0.28'
Dlaczego dodales manualnie wersje?

2022-04-09 11:42 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> +import org.springframework.boot.autoconfigure.domain.EntityScan;
Po co te importy?

2022-04-09 11:43 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ResponseEntity<ProductDto> updateProduct(@RequestBody ProductDto productDto) {
Brakuje pathVariable - przy edut chcemy to mieć, tak jak rozmawialiśmy w trakcie spotkania.

2022-04-09 11:44 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>  public class Product {
A gdzie relacja do grupy?

2022-04-09 11:44 UTC, adrianpaz commented on src/main/resources/application.properties
> +# suppress inspection "SpringBootApplicationProperties"
po co ten komentarz?

2022-04-09 11:45 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @Column(name = "name")
Nazwy kolumn piszemy z małej litery

2022-04-09 17:59 UTC, AgaChalat85 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @OneToMany
relacja  @OneToMany jest teraz ok, tylko, że adnotacja @OneToMany posiada kilka argumentów(targetEntity, mappedBy, cascade, fetch) i nie używamy tutaj  @JoinColumn, przepraszam, że nie opisałam tego dokładniej podczas ostatniego review

2022-04-09 20:00 UTC, gkowalczyk approved these changes

2022-04-09 22:44 UTC, dzejsiejcz requested changes
czy ten pull request ma załatwić task 13 i 22? jeśli tak to ok

2022-04-09 22:44 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    private Collection<Product> products = new ArrayList<Product>();
lepiej List<Product> products = new ArrayList<>(); ale to szczegół, ważniejsze na co zwróciła uwagę @AgaChalat85

2022-04-09 22:44 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/dto/GroupDto.java
> +    private ProductDto productDto;
powinna być List<ProductDto>, aczkolwiek klasa ta nie jest potrzebna do tego taska

2022-04-09 22:44 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<Group, Long> {
task 22

2022-04-09 22:44 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +public interface ProductRepository extends CrudRepository<Product, Long> {
task 22

2022-04-09 22:44 UTC, dzejsiejcz commented on src/main/java/com/kodilla/ecommercee/service/ProductDBService.java
> +public class ProductDBService {
task 22

2022-04-10 21:13 UTC, kuba1306 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @OneToMany
hmm teraz wdzę, że encja group została dodana przez Ciebie do głównego brancha

2022-04-12 13:34 UTC, rafalcisz1991 commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +public interface ProductRepository extends CrudRepository<Product, Long> {
To jest akurat w ramach mojego, zmergowanego już taska 21. Kuba tego nie pisał.

2022-04-12 21:14 UTC, dzejsiejcz approved these changes

2022-04-17 01:01 UTC, closed without merging

2022-04-17 01:01 UTC, kuba1306 commented
usuwam pull requesta po ostatniej rozmowie z Adrianem